[package]
name = "vp_doc_cli"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
node-semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
vp_static_config = { workspace = true }
vt_path = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true
